app/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

app/webapp/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

app_name='webapp'
urlpatterns = [
       path('', views.indexView.as_view(), name='index'),
       path('buscar/', views.search, name='search'),
       path('buscar/<busqueda>', views.search, name='search'),
       path('perfil/', views.profileView.as_view(), name='profile'),
       path('perfil/configuracion/<pk>', views.profile_configView.as_view(), name='profile_config'),
       path('perfil/configuracion/contrasenia/', views.change_password, name='change_pw'),
       path('perfil/remove/<int:res_id>', views.remove_reservation, name='remove_reservation'),
       path('productos/', views.productsView.as_view(), name='products'),
       path('productos/<int:index>/', views.productsView.as_view(), name='products'),
       path('productos/detalles/<int:pk>', views.detail_product, name='product_details'),
       path('productos/detalles/<int:pk>/<success>', views.detail_product, name='product_details'),
       path('mascotas/', views.petsView.as_view(), name='pets'),
       path('mascotas/<int:index>/', views.petsView.as_view(), name='pets'),
       path('mascotas/detalles/<pk>', views.detail_petView.as_view(), name='pet_details'),
       path('reservacion/<int:post_id>/', views.reservation, name='reservation'),
       path('reservacion/exitosa/', views.success_reservation, name='success_reservation'),
       path('contacto/', views.contactView, name='contact'),
       path('sucess_signin/', views.sucess_signin, name='sucess_signin'),
       path('registrarse/', views.signin, name='signin'),
       path('ingresar/', auth_views.LoginView.as_view(template_name='webapp/login.html'), name='login'),
       path('desconectar/', auth_views.LogoutView.as_view(template_name='webapp/logout.html',next_page='webapp:index'), name='logout'),
       path('restablecer_contraseña/', views.indexView, name='password_reset'),
    ]

app/webapp/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Postable(models.Model):
    name = models.CharField(max_length=45, null=False)
    img_url = models.CharField(max_length=64, null=False)
    price = models.IntegerField(null=False)
    description = models.CharField(max_length=255, null=False)
    class Meta:
        abstract = True

class Dog(Postable):
    TYPES = (
        ('Disponible', 'Disponible'),
        ('Reservado', 'Reservado'),
        ('Vendido','Vendido')
    )
    race = models.CharField(max_length=45, null=False)
    gender = models.CharField(max_length=1, null=False)
    birthdate = models.DateTimeField(null=False)
    status = models.CharField(max_length=45, null=False, choices=TYPES)
    def __str__(self):
        return super().name

    def get_age(self):
        today = datetime.date.today()
        return (today.year - self.birthdate.year) - int( (today.month, today.day) <
        (self.birthdate.month, self.birthdate.day))
        pass

class Article(Postable):
    TYPES = (
        ('C', 'Comestibles'),
        ('S', 'Atuendos'),
        ('A', 'Accesorios'),
        ('O', 'Otros')
    )
    stock = models.IntegerField(default=1,null=False)
    category = models.CharField(max_length=1, null=False, default='O', choices=TYPES)
    def __str__(self):
        return super().name
    pass

class Post(models.Model):
    TYPES = (
        ('D', 'Dog'),
        ('P', 'Product'),
    )
    dog = models.OneToOneField(Dog, on_delete=models.CASCADE, blank=True, null=True)
    product = models.OneToOneField(Article, on_delete=models.CASCADE, blank=True, null=True)
    type = models.CharField(max_length=1, choices=TYPES)# D - DOG // P - Product
    def __str__(self):
        if self.type == 'D':
            return 'Dog {0} - {1}'.format(self.id,self.dog.name)
        else:
            return 'Product {0} - {1}'.format(self.id,self.product.name)
    pass

class Reservation(models.Model):
    TYPES = (
        ('D', 'Dog'),
        ('P', 'Product'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, default=None)
    quantity = models.IntegerField(default=1, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True, default=None)
    type = models.CharField(max_length=1, choices=TYPES)# D - DOG // P - Product
    status = models.CharField(max_length=1, choices=(('A','Activa'),('F','Finalizada')), blank=True, null=True)
    reservation_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        if self.type == 'D':
            return 'Dog: {0} --> Usuario: {1}'.format(self.post.dog.name, self.user.email)
        else:
            return 'Producto: {0} --> Usuario: {1}'.format(self.post.product.name, self.user.email)

class Featured(models.Model):
    TYPES = (
        ('C', 'Carousel'),
    )
    feature = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True, default=None)
    type = models.CharField(max_length=1, choices=TYPES)# C - carousel
    def __str__(self):
        if self.feature.type == 'D':
            return 'Feature {0} -> {1}'.format(self.type, self.feature.dog.name)
        if self.feature.type == 'P':
            return 'Feature {0} -> {1}'.format(self.type, self.feature.product.name)
    pass

app/webapp/forms.py
import re
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User

class RegistrationForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),label='Nombre', max_length=64)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}),label='Apellido', max_length=64)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}),label='Correo', max_length=64)
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={'class':'form-control'}), max_length=128)
    password2 = forms.CharField(label='Repetir Contraseña', widget=forms.PasswordInput(attrs={'class':'form-control'}), max_length=128)

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Ambas contraseñas deben ser iguales')

    def clean_email(self):
        username = self.cleaned_data['email']
        try:
            User.objects.get(username = username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Ha ocurrido un error')

class ProductReservationForm(forms.Form):
    quantity = forms.IntegerField(
        label='Cantidad',
        min_value=1
        )

app/webapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import views
from django.contrib.auth import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Post, Featured, Reservation, Dog, Article
from django.utils import timezone
import datetime
from .forms import RegistrationForm, ProductReservationForm
from django.urls import reverse_lazy
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout


class indexView(generic.ListView):
    template_name = 'webapp/index.html'
    model = Featured

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class profileView(LoginRequiredMixin, generic.ListView):
    login_url = 'webapp:login'
    template_name = 'webapp/profile.html'
    model = Reservation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reservas_disponibles'] = 3 - \
            len(Reservation.objects.filter(
                type='D', user=self.request.user, status='A'))
        product_prices = []
        res = Reservation.objects.filter(user=self.request.user, status='A')
        for r in res:
            if r.type == 'P':
                product_prices.append(r.quantity * r.post.product.price)
            else:
                product_prices.append(0)
        context['product_prices'] = product_prices
        print(product_prices)
        return context

    def get_queryset(self):
        """ Queryset """
        if self.request.user.is_authenticated:
            return Reservation.objects.filter(user=self.request.user, status='A')


class profile_configView(LoginRequiredMixin, generic.edit.UpdateView):
    login_url = 'webapp:login'
    model = User
    fields = ['first_name', 'last_name']
    template_name = 'webapp/user_update_form.html'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('webapp:profile')


class petsView(generic.ListView):
    template_name = 'webapp/pets_list.html'
    context_object_name = 'object_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            i = self.kwargs['index']
            if i < 0:
                i = 1
            if i > len(Post.objects.filter(type='D'))//8 + 1:
                i = 1
            context['index'] = i
        except Exception as e:
            context['index'] = 1
        try:
            #context['total_objects'] = [i for i in range(50)]
            context['total_objects'] = [i for i in range(
                len(Post.objects.filter(type='D'))//8 + 1)]
            print("context buscado")
            print("mascotas: ", context['total_objects'])
        except Exception as e:
            print("Exception in petsView", e)
            context['total_objects'] = []
        return context

    def get_queryset(self):
        """ Queryset """
        try:
            i = self.kwargs['index']
        except:
            i = 1
        posts = Post.objects.filter(type='D')
        print("POSTS: ", posts)
        print("Test POSTS: ", Post.objects.all())
        post_list = []
        for p in posts:
            if p.dog.status == 'Disponible' or p.dog.status == 'Reservado':
                post_list.append(p)
        if len(posts) > 8:
            if i < 0:
                i = 1
            if i > len(post_list)//8 + 1:
                i = 1
            try:
                return post_list[(i-1)*8:i*8]
            except:
                print('Error')
                return []
        return post_list[:8]


class detail_petView(generic.DetailView):
    template_name = 'webapp/pet_details.html'
    model = Dog
    context_object_name = 'pet'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edad'] = timezone.now().year - \
            Dog.objects.filter(pk=1)[0].birthdate.year
        return context


def detail_product(request, pk, success=''):
    context = {}
    post = get_object_or_404(Post, pk=pk)
    context['post'] = post
    form = ProductReservationForm()
    if request.method == 'POST':
        form = ProductReservationForm(request.POST)
        if form.is_valid():
            if post.type == 'P':
                q = form.cleaned_data['quantity']
                if q <= post.product.stock:
                    r = None
                    try:
                        r = Reservation.objects.get(post__product=post.product)
                    except Exception as e:
                        print(e)
                        pass
                    if r:
                        reservation = r
                        reservation.quantity = reservation.quantity + q
                    else:
                        reservation = Reservation(
                            user=request.user,
                            post=post,
                            quantity=q,
                            type='P',
                            status='A',
                            reservation_date=timezone.now() - datetime.timedelta(hours=4)
                        )
                    reservation.save()
                    reservation.post.product.stock = post.product.stock - q
                    reservation.post.product.save()
                else:
                    form.add_error(
                        'quantity', 'La cantidad ingresada es superior al total de productos disponibles')
                    context['form'] = form
                    return render(request, 'webapp/product_details.html', context)
            return HttpResponseRedirect(reverse('webapp:product_details', kwargs={
                'pk': post.id,
                'success': 'reservacion exitosa'
            }))
    context['form'] = form
    context['success'] = success
    return render(request, 'webapp/product_details.html', context)


class detail_productView(generic.DetailView):
    template_name = 'webapp/product_details.html'
    model = Post
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class productsView(generic.ListView):
    template_name = 'webapp/products_list.html'
    context_object_name = 'object_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            i = self.kwargs['index']
            if i < 0:
                i = 1
            if i > len(Post.objects.filter(type='P'))//8 + 1:
                i = 1
            context['index'] = i
        except Exception as e:
            context['index'] = 1
        try:
            #context['total_objects'] = [i for i in range(50)]
            context['total_objects'] = [i for i in range(
                len(Post.objects.filter(type='P'))//8 + 1)]

        except:
            context['total_objects'] = []
        return context

    def get_queryset(self):
        """ Queryset """
        try:
            i = self.kwargs['index']
        except:
            i = 1
        posts = Post.objects.filter(type='P')
        if len(posts) > 8:
            if i < 0:
                i = 1
            if i > len(posts)//8 + 1:
                i = 1
            try:
                return Post.objects.filter(type='P')[(i-1)*8:i*8]
            except:
                print('Error')
        else:
            return Post.objects.filter(type='P')[:8]


def search(request, busqueda=''):
    context = {}
    query1 = []
    query2 = []
    try:
        search = request.POST['search']
    except Exception as e:
        print(e)
    try:
        query1 = Post.objects.filter(dog__name__istartswith=search)
        print(query1)
    except Exception as e:
        print(e)
    try:
        query2 = Post.objects.filter(product__name__istartswith=search)
        print(query2)
    except Exception as e:
        print(e)
    context['result1'] = query1
    context['result2'] = query2
    return render(request, 'webapp/search.html', context)


@login_required(login_url='webapp:login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            request.user.set_password(form.cleaned_data['new_password2'])
            request.user.save()
            return HttpResponseRedirect(reverse('webapp:profile'))
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'webapp/change_pw.html', {'form': form})


@login_required(login_url='webapp:login')
def reservation(request, post_id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            dog = get_object_or_404(Dog, pk=post_id)
            post = Post.objects.get(dog=dog)
            print(post)
            try:
                if post.type == 'P':
                    raise ValueError('Error producto')
                elif post.type == 'D':
                    if len(Reservation.objects.filter(user=request.user, type='D')) < 3:
                        reservation = Reservation(
                            user=request.user,
                            post=post,
                            type='D',
                            status='A',
                            reservation_date=timezone.now() - datetime.timedelta(hours=4)
                        )
                        reservation.save()
                        dogy = post.dog
                        dogy.status = 'Reservado'
                        dogy.save()
                    else:
                        return render(request, 'webapp/error_reservation.html', {

app/webapp/templates/webapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content='width=device-width, initial-scale=1,shrink-to-fit=no'>
    <title>{% block title %}Inicio{% endblock %}</title>
    {% load static %}
    {% load humanize %}
    <link href="{% static 'webapp/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'webapp/css/all.css' %}" rel="stylesheet">
    <style>
    </style>
    {% block style %}{% endblock %}
  </head>
  <body class="bg-dark">
    <div class="container bg-light px-1">
      <div class="container sticky-top bg-light px-0">
        <div class="row">
          <div class='col-auto mr-auto'>
            <h3><p><i class='fa fa-hospital-alt text-dark'></i> Clinica Veterinaria Del Norte</p></h3>
          </div>
          <div class="col-auto mt-1">
              {% if user.is_authenticated %}
                <div class="row float-right">
                  <div class="col-auto mt-1">
                    <h5><p>{{ user.get_full_name|truncatechars:20 }}</p></h5>
                  </div>
                  <div class="col-auto pl-0 pr-0">
                    <a class="btn btn-secondary btn-sm" role='button' href="{% url 'webapp:profile' %}">Mi cuenta <i class="fas fa-cog"></i></a>
                  </div>
                  <div class="col-auto pl-1">
                    <a class="btn btn-secondary btn-sm" role='button' href="{% url 'webapp:logout' %}">Salir <span class='fas fa-sign-out-alt fa-lg'></span></a>
                  </div>
                </div>
                
              {% else %}
              <div class="col-auto mb-2">
                <a class="btn btn-primary btn-sm" role="button" href="{% url 'webapp:login' %}">Ingresar <span class='fas fa-sign-in-alt fa-lg'></span></a>
                <a class="btn btn-primary btn-sm" role="button" href="{% url 'webapp:signin' %}">Registrarse <span class='fa fa-user-plus fa-lg'></span></a>
              </div>
              {% endif %}
          </div>
        </div>
        <div class="row">
          <div class="col-12">
              <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand m-0" href="{% url 'webapp:index' %}"><i class="fa fa-dog fa-flip-horizontal fa-md"></i> <p class='d-inline d-lg-none'>Menu</p></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                  data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    {% block nav_items %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'webapp:index' %}">Inicio<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'webapp:products' %}">Productos</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'webapp:pets' %}">Mascotas</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'webapp:contact' %}">Contacto</a>
                    </li>
                    {% endblock %}
                  </ul>
                  <form class="form-inline my-2 my-lg-0" method='post' action="{% url 'webapp:search' %}">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" name='search' id='search' type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit" id="buscar">Buscar <i class="fa fa-search"></i></button>
                  </form>
                </div>
              </nav>
          </div>
        </div>
      </div>
      <div class="container px-0">
        {% block content %}
        {% endblock %}
        <hr>
        <div class="row justify-content-center">
          <div class="col-auto">
            <h5 class='lead'><i class='fa fa-copyright'></i> Clinica Veterinaria Del Norte</h5>
          </div>
        </div>
      </div>
    </div>
    <script src="{% static 'webapp/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'webapp/js/bootstrap.bundle.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

app/webapp/templates/webapp/contact.html
{% extends 'webapp/base.html' %}

{% block title %}Contacto{% endblock %}
{% block styles %}
  <style>
    .contact_div {
      margin: 10px 10px;
    }
  </style>
{% endblock %}
{% block nav_items %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'webapp:index' %}">Inicio</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'webapp:products' %}">Productos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'webapp:pets' %}">Mascotas</a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'webapp:contact' %}">Contacto<span class="sr-only">(current)</span></a>
  </li>
{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-12 mt-1">
      <div class="card border-dark mb-3">
        <div class="card-header">Informacion de Contacto</div>
        <div class="card-body text-dark">
          <h5 class=""><i class='fa fa-phone mr-1'></i>Telefonos de contacto: </h5>
          <p class="card-text ml-1">{{ telf }}</p>
          <h5 class=""><i class='fa fa-address-book mr-1'></i>Direccion: </h5>
          <p class="card-text ml-1">{{ direction }}</p>
          <h5 class=""><i class='fa fa-envelope mr-1'></i>Correos de contacto: </h5>
          <p class="card-text ml-1">{{ emails }}</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/webapp/templates/webapp/profile.html
{% extends 'webapp/base.html' %}

{% block title %}Mi Cuenta{% endblock %}
{% load static %}
{% load humanize %}
{% block nav_items %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'webapp:index' %}">Inicio</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'webapp:products' %}">Productos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'webapp:pets' %}">Mascotas</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'webapp:contact' %}">Contacto</a>
  </li>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="row alert-dark m-0">
  <div class="col-12 col-md-6">
    <h5 class='pt-2 text-dark'>Lista de reservaciones</h5>
    <p type="button" class="btn pl-0 mb-0">
      Reservas de perros disponibles <span class="badge badge-light">{{ reservas_disponibles }}<i class='fa fa-dog ml-1'></i></span>
    </p>
  </div>
  <div class="col-12 col-md-6 mt-1 justify-content-md-end align-items-start d-flex">
    <div class="btn-group" role="group" aria-label="Basic example">
      <a class="btn btn-secondary btn-sm rounded-left" role="button" href="{% url 'webapp:profile_config' pk=user.id %}">Actualizar Datos<i class='fa fa-user-edit ml-1'></i></a>
      <a class="btn btn-secondary btn-sm rounded-right" role="button" href="{% url 'webapp:change_pw' %}">Cambiar Contraseña<i class='fa fa-user-cog ml-1'></i></a>
    </div>
  </div>
</div>
<div class='row m-0 table-responsive'>
  <table class="table table-dark table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Precio</th>
        <th class='d-none d-md-block' scope="col">Cantidad</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for res in object_list %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        {% if res.type == 'D'%}
        <td>{{ res.post.dog.name }}</td>
        <td class=''>{{ res.post.dog.price|intcomma }}<i class='fa fa-dollar-sign ml-1'></i></td>
        <td class='d-none d-md-block'>- - - -</td>
        <td><button class='btn btn-danger float-right btn-sm' role='button' data-toggle="modal" data-target="#res{{ res.id }}">Eliminar</button></td>
        {% elif res.type == 'P'%}
        <td>{{ res.post.product.name }}</td>
        {% with x=forloop.counter0 %}
        {% for p in product_prices %}
        {% if x == forloop.counter0 %}<td class=''>{{ p|intcomma }}<i class='fa fa-dollar-sign ml-1'></i></td>{% endif %}
        {% endfor %}
        {% endwith %}
        <td class='d-none d-md-block'>{{ res.quantity }}</td>
        <td><button class='btn btn-danger float-right btn-sm' role='button' data-toggle="modal" data-target="#res{{ res.id }}">Eliminar</button></td>
        {% endif %}
      </tr>
      {% empty %}
      <p class='alert alert-info mb-0 lead'>Usted no posee reservas actualmente</p>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class='row'>
  {% for res in object_list %}
  <div class="modal fade" id="res{{ res.id }}" tabindex="-1" role="dialog" aria-labelledby="res{{ res.id }}Label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="res{{ res.id }}Label">Eliminar Reserva</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% if res.type == 'D'%}
          Esta seguro que desea eliminar la reserva del perro <b>{{ res.post.dog.name }}</b>?
          {% elif res.type == 'P'%}
          Esta seguro que desea eliminar la reserva del producto <b>{{ res.post.product.name }}</b>?
          {% endif %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <form class="form" action="{% url 'webapp:remove_reservation' res.id %}" method="post">
          {% csrf_token %}
          <input type="submit" value="Eliminar" class="btn btn-danger">
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else%}
<div class='row m-0'>
  <div class='col-12 alert alert-danger'>Para ver el contenido de esta pagina debe <a class='btn btn-link pt-1 pl-0' href={% url "webapp:login" %}>iniciar sesion</a></div>
</div>
{% endif %}
{% endblock %}

app/webapp/templates/webapp/search.html
{% extends 'webapp/base.html' %}

{% block title %}Buscar{% endblock title %}
{% load static %}
{% block content %}
<div class='row mt-2'>
    {% for post in result1 %}
    <div class="col-auto mb-2 ml-auto mr-auto ml-md-0 mr-md-0">
        <div class="card" style="width: 15rem;">
          <img src="{% static post.dog.img_url %}" class="card-img-top" alt="dog image"height="150px">
          <div class="card-body">
            <h5 class="card-title">{{ post.dog.name }}
              {% if post.dog.status == 'Disponible' %}<span class="badge badge-primary">{{ post.dog.status }}</span>
              {% elif post.dog.status == 'Reservado' %}<span class="badge badge-warning">{{ post.dog.status }}</span>
              {% endif %}
            </h5>
            <h6 class="card-subtitle mb-2 text-success">{{ post.dog.price }}$</h6>
            <p class="card-text">Puddle - Macho - 10 años
              <br><hr></p>
            <a href="{% url 'webapp:pet_details' post.dog.id %}" class="btn btn-primary btn-md w-100">Ver mas</a>
          </div>
        </div>
    </div>
    {% endfor %}
    {% for post in result2 %}
    <div class="col-auto mb-2 ml-auto mr-auto ml-md-0 mr-md-0">
        <div class="card" style="width: 15rem;">
          <img src="{% static post.product.img_url %}" class="card-img-top" alt="product image"height="150px">
          <div class="card-body">
            <h5 class="card-title">{{ post.product.name }}</h5>
            <h6 class="card-subtitle mb-2 text-success">{{ post.product.price }}$</h6>
            <p class="card-text">Disponibles: {{ post.product.stock }}
              <br><hr></p>
            <a href="{% url 'webapp:product_details' post.id %}" class="btn btn-primary btn-md w-100">Ver mas</a>
          </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}